defaults:
  - default
  - override dataset: scannet
  - override encoder: base_encoder
  - override mapping: semantic_voxel_map
  - override vis: null # Choose the visualizer - can be either rerun or null
  - _self_

# Choose any suitable folder for saving the results
eval_out: eval_out/radseg

load_external_gt: False
prediction_thresh: 0.1 # Threshold after which a prediction is made.
prompt_denoising_thresh: 0.5 # Confidence threshold below which the target class prompt is removed
k: 5 # K nearest neighbor value for aligning voxels. Set to 0 to impose a 1-to-1 mapping (0 distance)

# For running the evaluation script on multiple scenes at the same time.
hydra:
  sweeper:
    params:
      dataset.scene_name: scene0050_00, scene0231_01, scene0378_02, scene0050_01, scene0231_02, scene0518_00, scene0011_00, scene0050_02, scene0378_00, scene0011_01, scene0231_00, scene0378_01

dataset:
  path: ??? # Add the path to the dataset
  scene_name: scene0231_01
  rgb_resolution: [640, 864]
  depth_resolution: [640, 864]
  frame_skip: 10

encoder:
  _target_: radseg.radseg.RADSegEncoder
  model_version: c-radio_v3-b
  lang_model: siglip2
  compile: false
  amp: false
  slide_crop: 336
  slide_stride: 112
  scga_scaling: 10.0
  scra_scaling: 10.0
  # Set predict to true for probability space aggregation and set sam_refinement to true for RADSeg+ when doing probability space aggregation.
  sam_refinement: false
  predict: false
  sam_ckpt: sam_vit_h_4b8939.pth # Path to the SAM checkpoint

mapping:
  vox_size: 0.05 # 5cm voxels
  vox_accum_period: 4
  max_pts_per_frame: -1

querying:
  text_query_mode: labels

classes_to_ignore: ['otherprop', 'otherstructure', 'otherfurniture']